### ISSUE TITLE
Sample yml configuration issuer->issuers

### ISSUE THREAD

**Issue by rwinch** [jzheaux/spring-security#8]
### Summary

Update sample to read configuration from issuers

Right now the config looks like:

```
spring:
  security:
    oauth2:
      resourceserver:
        issuer:
```

I think it makes more sense to use issuers since it has the possibility of having multiple issuers:

```
spring:
  security:
    oauth2:
      resourceserver:
        issuers:
```
