### ISSUE TITLE
Rethink resourceserver in sample YML configuration

### ISSUE THREAD

**Issue by rwinch** [jzheaux/spring-security#9]
### Summary

I think we should consider renaming 

```
spring:
  security:
    oauth2:
      resourceserver:
```

to

```
spring:
  security:
    oauth2:
      server:
        resource:
```

or

```
spring:
  security:
    oauth2:
      resource-server:
```

Related #2

**Comment by jgrandja** [comment]
For the base property, my vote goes for:

```
spring:
  security:
    oauth2:
      resource-server:
```
